### ISSUE TITLE
Syntax error in regex

### ISSUE THREAD

**Issue by liborm85** [rviscomi/trunk8#57]
Hello.

I found problem in function getHtmlArr with regex on line 54.
Problem is with character "*" which causes a syntax error (but in trunk8 probably work), tested on: https://regex101.com/r/zN2kA0/1
Here is regex without this syntax error https://regex101.com/r/pU2oZ9/1

Thanks for fix.

**Comment by rviscomi** [comment]
@liborm85 thanks for reporting this. Can you file a pull request?

**Comment by liborm85** [comment]
https://github.com/rviscomi/trunk8/pull/58
