### ISSUE TITLE
Truncates all characters

### ISSUE THREAD

**Issue by s1h4d0w** [rviscomi/trunk8#64]
I am using Trunk8 for a website where it needs to truncate names in a table cell. When the website is viewed on mobile some non-essential things get trucated.

Yesterday on my Mac on Firefox 37.0.2 it worked without a problem, but after checking today on my Windows machine the text does not show up at all. This is on Firefox 37.0.2 and Chrome 42.0.2311.135. The complete text is in the "title" tag of the table-cell with the truncate class. If I press Ctrl + F5 it works correctly, but if I then just press F5 or close and reopen the page the text is gone again.

I have included jQuery 1.7 in my head and have called $(".truncate").trunk8(); below that.

On pageload:
![On pageload](https://cloud.githubusercontent.com/assets/5654654/7489474/51ae3c6c-f3d7-11e4-8b74-fd0664b68665.png)

After pressing Ctrl + F5:
![After pressing Ctrl + F5](https://cloud.githubusercontent.com/assets/5654654/7489475/5b0de744-f3d7-11e4-808f-076e8a7103d2.png)

**Comment by rviscomi** [comment]
Do you have a link to view the markup? (even if it's just a simple jsfiddle example that shows your problem, that would be fine)

Also, just a tip that you shouldn't need to load jQuery and trunk8 in the document head. You should be able to load these scripts at the end of the document, just before the closing body tag. I don't think it's causing the problem you're describing, but it helps page load performance.

**Comment by s1h4d0w** [comment]
Hi Rick,

 

Thank you for contacting me, much appreciated. I’ve tried using Trunk8 in a jsFiddle bit it appeared to be working fine.

 

As the project is in a very early stage I have no problem giving you some login credentials, the site is in Dutch but I can point you around:

 

Visit: http://www.nickbetting.nl/yd/ 

 

Username: Rick Viscomi

Password: testing123

Wekelijkse toegangscode: 0000

 

After you’ve been logged in click the “ga naar beheerpaneel” link just below the logo. Now you can click either “Locaties” or “Medewerkers” to view where it’s going wrong. I’m using Windows 8.1 with Firefox 37.0.2, Chrome 42.0.2311.135 m, Internet Explorer 11 and Opera 29 and it works on none of those. If I log in with my iPhone under Safari it works without a problem.

 

Thank you so much for the help!

 

 

Kind regards,

 

Nick Betting

 

Van: Rick Viscomi [mailto:notifications@github.com] 
Verzonden: donderdag 7 mei 2015 05:28
Aan: rviscomi/trunk8
CC: s1h4d0w
Onderwerp: Re: [trunk8] Truncates all characters (#64)

 

Do you have a link to view the markup? (even if it's just a simple jsfiddle example that shows your problem, that would be fine)

Also, just a tip that you shouldn't need to load jQuery and trunk8 in the document head. You should be able to load these scripts at the end of the document, just before the closing body tag. I don't think it's causing the problem you're describing, but it helps page load performance.

**Comment by rviscomi** [comment]
It seems to be working for me on Chrome Mac, but one thing I noticed is that your trunk8 class is on a `td` element. Try structuring your markup like this instead:

    <td><span class="trunk8">text</span></td>

I think the default styles on the td may be interfering with the way the text gets rendered.

Let me know if that helps.

**Comment by s1h4d0w** [comment]
Hi Rick,

That fixed it, thanks a bunch. I assumed it would work on any element, I saw some reported issues on other elements but didn't see any for <td>'s. By putting the text in a separate <span> it worked flawlessly.

Thanks and keep up the good work!
