### ISSUE TITLE
Problem with Chrome ! 

### ISSUE THREAD

**Issue by naimhiq** [rviscomi/trunk8#78]
Hi, 

And I have the same problem. In chrome instead of trunc in two lines it is doing it on one line  but in firefox it is working well. 

Any suggestion  ? 

/Naim

**Comment by rviscomi** [comment]
Can you provide any steps to reproduce the issue or maybe a code sample (ie jsfiddle)? Thanks.

**Comment by naimhiq** [comment]
Hi Rick, 

I actually fixed the issue :).  The problem was with my line-heights on elements that I had in rem units but  as long as I changed in Unitless line-heights so it is rendering fine both in Chrome now and Firefox

Thanks for help ! 

/Naim
